# add this file
# default MySQL root password is 123456
# default version:5.7
# if you want to change mysql version: 1. change file: ./.env_all 2. add parameter: docker run -e DB_MYSQL_VERSION=${your_version}.
# tip: please clear all files in your compose’folder.

version: '3.8'

services:

  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_NAME}
    restart: always
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
     - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}

volumes:
  mysql:
  
networks:
  default:
      name: "${APP_NAME}"
